nav:
  - Home: index.md
  - How does Kandle work?: 
    - High Level View: howitworks/overview.md
    - Fees Mechanism: howitworks/fees_mechanism.md
    - Pool Participation Process: howitworks/pool_participation_process.md
    - Rewarding Process: howitworks/rewarding_process.md
    - Burning Process: howitworks/burning_process.md
    - Fuel Collector: howitworks/fuel_collector.md
  - Governance Token:
    - Token Distribution: governance_token/token_distribution.md
    - Private Sale: governance_token/private_sale.md
    - Public Sale: governance_token/public_sale.md
    - Trasury & Liquidity Management: governance_token/treasury_management.md
  - Background:
    - background/index.md
    - Proof-of-Burn (PoB): background/pob.md
    - Decentralized Exchange: background/dex.md
    - BSC vs ETH: background/bsc_vs_eth.md
  - Roadmap: roadmap.md
  # - Simulations: simulations.md
  - Market impact: market_impact.md
  - FAQ: faq.md
  - Join Us: joinus.md

site_name: Kandle Platform Docs
site_description: Kandle Platform Documentation
site_author: Kandle Platform Community
copyright: "Copyright © 2022, Maintained by the Kandle Team."
edit_uri: ""
use_directory_urls: false
repo_name: 'KandleFinance/docs-site'
repo_url: 'https://github.com/KandleFinance/docs-site'


theme:
  name: 'material'
  custom_dir: overrides
  language: en
  font:
    text: Catamaran
    code: Roboto Mono
  palette:
    - scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/toggle-switch 
        name: Switch to dark mode
    - scheme: slate 
      primary: dark-kandle
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  logo: assets/images/logo.svg
  features:
    - toc.follow
    - content.tabs.link
    - content.code.annotate
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - announce.dismiss

extra_css:
  - assets/stylesheets/extra.css

markdown_extensions:
    - attr_list
    - admonition
    - def_list
    - toc:
        title: On this page
        permalink: ⚓︎
    - md_in_html
    - pymdownx.arithmatex
    - pymdownx.tasklist:
        custom_checkbox: True
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - codehilite
    - pymdownx.snippets
    - abbr
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search

extra:
  generator: false
  analytics:
    provider: google
    property: G-WW50WKY212
  social:
    - icon: 'material/web'
      link: 'https://www.kandle.finance'
    - icon: 'material/twitter'
      link: 'https://twitter.com/KandleFinance'
    - icon: 'fontawesome/brands/telegram'
      link: 'https://t.me/+Mfeav0KtCOc1Mjk0'
    - icon: 'material/github'
      link: 'https://github.com/KandleFinance'